[Workspace]
Home=..\
AppSrcPath=AppSrc
AppHTMLPath=AppHtml
BitmapPath=.
IdeSrcPath=IdeSrc
DataPath=Data
DDSrcPath=DDSrc
HelpPath=.
ProgramPath=Programs
FileList=Data\Filelist.cfg
Description=SingleSignOnDemo
